apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: data-claim
    label:
      app: mysql
  spec:
    accessModes: 
    - ReadWriteOnce
    storageClass: gp2
    volumeMode: Filesystem
    resources:
      requests: 
        storage: 1Gi

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: init-claim
    label:
      app: mysql
  spec:
    accessModes: 
    - ReadWriteOnce
    storageClass: gp2
    volumeMode: Filesystem
    resources:
      requests: 
        storage: 1Gi
